MobilePhoneStoreEcommerce/MobilePhoneStoreEcommerce/Controllers/CartController.cs
using MobilePhoneStoreEcommerce.Core;
using MobilePhoneStoreEcommerce.Core.Domain;
using MobilePhoneStoreEcommerce.Core.Services;
using MobilePhoneStoreEcommerce.Core.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MobilePhoneStoreEcommerce.Controllers
{
    public class CartController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private IAccountAuthentication _accountAuthentication; 

        public CartController(IUnitOfWork unitOfWork, IAccountAuthentication accountAuthentication)
        {
            this._unitOfWork = unitOfWork;
            this._accountAuthentication = accountAuthentication;
        }
        public ActionResult Index(int customerID)
        {

            Customer customer = this._unitOfWork.Customers.Get(customerID);
            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            return View(new CartViewModel() { CustomerID = customerID, CustomerAddress = customer.DeliveryAddress});
        }
    }
}

MobilePhoneStoreEcommerce/MobilePhoneStoreEcommerce/Controllers/HomeScreenController.cs
using MobilePhoneStoreEcommerce.Models.ControllerModels;
using MobilePhoneStoreEcommerce.Models.ViewModels;
using MobilePhoneStoreEcommerce.Persistence;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobilePhoneStoreEcommerce.Controllers
{
    public class HomeScreenController : Controller
    {
        private ApplicationDbContext _context;
        public HomeScreenController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: HomeScreen
        public ActionResult Index(int page = 1, int pagesize = 8)
        {
            var allProducts = new ProductModel().allAvailableProducts(page, pagesize);
            return View(allProducts);
        }

        public ActionResult Details(int id)
        {
            var product = new ProductModel().productDetail(id);
            ViewBag.ProId = id;
            return View(product);
        }
        public ActionResult Store(int page = 1, int pagesize = 8)
        {
            ViewBag.Action = "Store";
            var viewModel = new StoreViewModels()
            {
                allAvailableProducts = new ProductModel().allAvailableProducts(page, pagesize),
                allProducers = new ProductModel().allProducers()
            };
            return View(viewModel);
        }

        public ActionResult Producer(int id, int page = 1, int pagesize = 8)
        {
            //var productOfProducer = new ProductModel().allAvailableProductsOfProducer(id, page, pagesize);
            //return View(productOfProducer);
            ViewBag.Producer = ViewBag.Action = "Producer";
            ViewBag.ProducerName = new ProductModel().getProducerNameById(id);
            var viewModel = new StoreViewModels()
            {
                allAvailableProducts = new ProductModel().allAvailableProductsOfProducer(id, page, pagesize),
                allProducers = new ProductModel().allProducers()
            };
            return View("Store", viewModel);
        }

        public ActionResult ProductsOfSearch(string search = "", int page = 1, int pagesize = 8)
        {
            ViewBag.Action = "Search";
            ViewBag.Search = search;
            var viewModel = new StoreViewModels()
            {
                allAvailableProducts = new ProductModel().allAvailableProductsOfSearch(search, page, pagesize),
                allProducers = new ProductModel().allProducers()
            };
            return View("Store", viewModel);
        }

        public ActionResult Category(int id, int page = 1, int pagesize = 8)
        {
            ViewBag.Action = "Cat";
            ViewBag.CatName = new ProductModel().getCatNameById(id);
            var viewModel = new StoreViewModels()
            {
                allAvailableProducts = new ProductModel().allAvailableProductsOfCategory(id, page, pagesize),
                allProducers = new ProductModel().allProducers()
            };
            return View("Store", viewModel);
        }
    }
}

MobilePhoneStoreEcommerce/MobilePhoneStoreEcommerce/Controllers/SellerController.cs
using MobilePhoneStoreEcommerce.Core;
using MobilePhoneStoreEcommerce.Core.Services;
using MobilePhoneStoreEcommerce.Core.ViewModels;
using MobilePhoneStoreEcommerce.Persistence.Consts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace MobilePhoneStoreEcommerce.Controllers
{
    public class SellerController : Controller
    {
        private IUnitOfWork _unitOfWork;
        private IAccountAuthentication _accountAuthentication;
        public SellerController(IUnitOfWork unitOfWork, IAccountAuthentication accountAuthentication)
        {
            this._unitOfWork = unitOfWork;
            this._accountAuthentication = accountAuthentication;
        }
        public ActionResult Index(int sellerID)
        {
            if (!IsAuthorized(sellerID))
                return RedirectToAction("Login", "Account", new { roleID = RoleIds.Seller });

            var productForSellerViewModel = new ProductForSellerViewModel() { SellerID = sellerID };

            return View(productForSellerViewModel);
        }

        public ActionResult AddNewProduct(int sellerID)
        {
            if (!IsAuthorized(sellerID))
                throw new HttpResponseException(HttpStatusCode.Unauthorized);

            var productForSellerViewModel = new ProductForSellerViewModel() { SellerID = sellerID };

            return View(productForSellerViewModel);
        }
        public ActionResult UpdateProduct(int productID, int sellerID)
        {
            if (!IsAuthorized(sellerID))
                throw new HttpResponseException(HttpStatusCode.Unauthorized);

            var product = this._unitOfWork.Products.Get(productID);

            if (product == null)
                throw new HttpResponseException(System.Net.HttpStatusCode.NotFound);

            var productForSellerViewModel = new ProductForSellerViewModel();

            productForSellerViewModel.ProductID = product.ID;
            productForSellerViewModel.SellerID = sellerID;

            return View(productForSellerViewModel);
        }

        private bool IsAuthorized(int sellerID)
        {
            var session = Session[SessionNames.SellerID];
            if (!this._accountAuthentication.IsAuthentic(sellerID, session))
                return false;

            return true;
        }
    }
}

MobilePhoneStoreEcommerce/MobilePhoneStoreEcommerce/Views/Shared/MainLayout.cshtml
@using MobilePhoneStoreEcommerce.Persistence.Consts

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
	<title>Mobilestore Website Template | Home :: W3layouts</title>
	<meta name="keywords" content="Mobilestore iphone web template, Android web template, Smartphone web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	<link href="~/Assets/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" href="~/Assets/css/responsiveslides.css">
	@*<script src="~/Scripts/jquery-3.4.1.js"></script>*@
	<script src="~/Assets/js/jquery.min.js"></script>
	<script src="~/Assets/js/responsiveslides.min.js"></script>

</head>
<body style="width: 1329px;">
	<div class="wrap" >
		<!----start-Header---->
		<div class="header">
			<!--Search-->
			<div class="search-bar">
                <form action="/HomeScreen/ProductsOfSearch">
                    @Html.AntiForgeryToken()
                    <input type="text" value="@ViewBag.search" name="search"><input type="submit" value="Search" />
                </form>
			</div>
			<div class="clear"> </div>
			<div class="header-top-nav">
                <ul>
                    @if (Session[SessionNames.SellerID] != null)
                    {
                        <li><a href="@Url.Action("Index", "Seller", new { sellerID = Session[SessionNames.SellerID]})">Seller</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Login", "Account", new { roleID = RoleIds.Seller})">Seller</a></li>
                    }


                    @if (Session[SessionNames.CustomerID] == null)
                    {
                        <li><a href="@Url.Action("Register", "Account")">Register</a></li>
                        <li><a href="@Url.Action("Login", "Account")">Login</a></li>
                    }
                    else
                    {
                        <li><a href="@Url.Action("Info", "Customer", new { customerID = Session[SessionNames.CustomerID]})">My Account</a></li>
                        <li><a href="@Url.Action("Logout", "Account", routeValues: new { sessionName = SessionNames.CustomerID })">Logout</a></li>
                    }
                    <li>
                        @if (Session[SessionNames.CustomerID] != null)
                        {
                            <a href="@Url.Action("Index", "Cart", new { customerID = Session[SessionNames.CustomerID]})">
                                <img class="cart-image" src="@Url.Content("~/Assets/images/cart-icon.png")" style="height:50px; width: 50px; padding-top: 10px" />
                            </a>
                        }
                        else
                        {
                            <a href="@Url.Action("Login", "Account", new { roleID = RoleIds.Customer })">
                                <img src="@Url.Content("~/Assets/images/cart-icon.png")" style="height:50px; width: 50px; padding-top: 10px" />
                            </a>
                        }

                    </li>
                </ul>
			</div>
			<div class="clear"> </div>
		</div>
	</div>
	<div class="clear"> </div>
	<div class="top-header" style="margin-left: 2rem; margin-right: 2rem;">
		<div class="wrap">
			<!--Dropdown list-->
			@RenderPage("/Views/HomeScreen/ListOfCategory.cshtml")
			<!----start-logo---->
			<div class="logo">
				<a href="@Url.Action("Index", "HomeScreen")"><img src="~/Assets/images/logo.png" title="logo" /></a>
			</div>
			<!----end-logo---->
			<!----start-top-nav---->
			<div class="top-nav">
				<ul>
					<li><a href="@Url.Action("Index", "HomeScreen")">Home</a></li>
					<li><a href="@Url.Action("Store", "HomeScreen")">Store</a></li>
				</ul>
			</div>
			<div class="clear"> </div>
		</div>
	</div>
	<!----End-top-nav---->
	<!----End-Header---->

	@RenderBody()

	<div class="footer" style="margin-top: 3rem; margin-right: -2rem;">
		<div class="wrap">
			<div class="section group">
				<div class="col_1_of_4 span_1_of_4">
					<h3>About us</h3>
					<p>Products of group of IT faculties, University of Science and Technology</p>
				</div>
				<div class="col_1_of_4 span_1_of_4">
					<h3>News</h3>

				</div>
				<div class="col_1_of_4 span_1_of_4">
					<h3>Location</h3>
					<p>Street 1, Vo Van Ngan, Thu Duc, Ho Chi Minh City</p>
					<h3>Phone number</h3>
					<p>080-1234-56789</p>
					<p>080-1234-56780</p>
				</div>
				<div class="col_1_of_4 span_1_of_4 footer-lastgrid">
					<h3>News-Letter</h3>
                    <form>
                        @Html.AntiForgeryToken()
                        <input type="text"><input type="submit" value="go" />
                    </form>
					<h3>Follow Us:</h3>
					<ul>
						<li><a href="#"><img src="~/Assets/images/twitter.png" title="twitter" />Twitter</a></li>
						<li><a href="#"><img src="~/Assets/images/facebook.png" title="Facebook" />Facebook</a></li>
						<li><a href="#"><img src="~/Assets/images/rss.png" title="Rss" />Rss</a></li>
					</ul>
				</div>
			</div>
		</div>

		<div class="clear"> </div>
		<div class="wrap">
			<div class="copy-right">
				<p>&copy; 2013 Mobile Store. All Rights Reserved | Design by  <a href="http://w3layouts.com/">W3Layouts</a></p>
			</div>
		</div>
	</div>
</body>
</html>